### ISSUE TITLE
Error: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"

### ISSUE THREAD

**Issue by andrewpollock** [dsanders11/json-schema-validate-action#20]
Hi,

I'm having a hard time understanding what the problem might be here...

**Objective**: validate PRs changing a JSON Schema definition itself for correctness

**Implementation**: https://github.com/ossf/osv-schema/commit/1c585fde4e1157228202db652a85f408149a0e46

**Expected outcome**: the change to `validation/schema.json` is validated for correctness, and any problems surfaced with clear and actionable feedback

**Actual outcome**: `Error: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"` is opaque about whether this is a problem with the PR or a misconfiguration of the Action

**Comment by andrewpollock** [comment]
https://github.com/ossf/osv-schema/pull/260 is the PR exhibiting this problem

**Comment by dsanders11** [comment]
Thanks for opening an issue! From the linked implementation, it looks like you're using an older version that didn't support that draft version. Can you try using the latest v1.2.0?

**Comment by andrewpollock** [comment]
Thank you for your speedy response and I have no idea how I came to pin at a version older than the latest 🤦‍♂️

**Comment by dsanders11** [comment]
@andrewpollock, if using the latest version fixed your error, could you go ahead and close out this issue? Thanks!

**Comment by andrewpollock** [comment]
I believe this to be a non-issue since upgrading to the latest version.
